export enum OperationTransactionType {
  noApply = 'NA',
  deposit = 'DEPOSIT',
  reversal_deposit = 'REVERSAL_DEPOSIT',
  chargeback = 'CHARGEBACK',
  reversal_chargeback = 'REVERSAL_CHARGEBACK',
  credit = 'CREDIT',
  reversal_credit = 'REVERSAL_CREDIT',
  debit = 'DEBIT',
  reversal_debit = 'REVERSAL_DEBIT',
  withdrawal = 'WITHDRAWAL',
  reversal_withdrawal = 'REVERSAL_WITHDRAWAL',
  refund = 'REFUND',
  reversal_refund = 'REVERSAL_REFUND',
  payment = 'PAYMENT',
  reversal_payment = 'REVERSAL_PAYMENT',
  purchase = 'PURCHASE',
  reversal_purchase = 'REVERSAL_PURCHASE',
  extra_cash = 'EXTRACASH',
  reversal_extra_cash = 'REVERSAL_EXTRACASH',
}
