export enum BoldStatusEnum {
  NO_TRANSACTION_FOUND = 'NO_TRANSACTION_FOUND',
  PROCESSING = 'PROCESSING',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
}
