module.exports = {
  apps: [
    {
      name: 'b2crypto-microservices',
      script: './dist-pm2/apps/b2crypto/main-microservices.js',
      watch: ['./dist-pm2/apps/b2crypto/main-microservices.js'],
      exp_backoff_restart_delay: 100,
      instances: '1',
      exec_mode: 'cluster',
      //wait_ready: true,
      env: {
        ENVIRONMENT: 'DEV',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_NAME: 'b2crypto',
        DATABASE_URL: 'mongodb://localhost:27017/b2crypto',
        PORT: 3000,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST: 'localhost',
        RABBIT_MQ_PORT: 5672,
        RABBIT_MQ_QUEUE: 'DEV',
        RABBIT_MQ_USERNAME: 'admin',
        RABBIT_MQ_PASSWORD: 'admin',
        DATABASE_REDIS_HOST: 'localhost',
        DATABASE_REDIS_USERNAME: 'b2crypto',
        DATABASE_REDIS_PASSWORD: 'b2crypto',
        DATABASE_REDIS_PORT: 6379,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: true,
        TZ: 'UTC',
      },
      env_prod: {
        ENVIRONMENT: 'PROD',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_URL: '',
        PORT: 8080,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST: '',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'PROD',
        RABBIT_MQ_USERNAME: 'b2crypto',
        RABBIT_MQ_PASSWORD: '',
        DATABASE_REDIS_HOST: '',
        DATABASE_REDIS_USERNAME: 'b2crypto',
        DATABASE_REDIS_PASSWORD: '',
        DATABASE_REDIS_PORT: 12145,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
      },
      env_stage: {
        ENVIRONMENT: 'STAGE',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_URL:
          'mongodb+srv://b2crypto:SFh59fK9mmM2ln1L@stage-b2crypto.hwml0km.mongodb.net/?retryWrites=true&w=majority&appName=stage-b2crypto',
        PORT: 8080,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST:
          'b-4dfa36c9-e0d6-4949-a093-8352b12f782d.mq.us-west-1.amazonaws.com',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'STAGE',
        RABBIT_MQ_USERNAME: 'b2crypto',
        RABBIT_MQ_PASSWORD: 'RvEEpLfH87C2rs482lOy5L6xhjC6y90b',
        DATABASE_REDIS_HOST: '',
        DATABASE_REDIS_USERNAME: 'b2crypto',
        DATABASE_REDIS_PASSWORD: '',
        DATABASE_REDIS_PORT: 12145,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
      },
    },
    {
      name: 'b2crypto-gateway',
      script: './dist-pm2/apps/b2crypto/main-gateway.js',
      watch: ['./dist-pm2/apps/b2crypto/main-gateway.js'],
      exp_backoff_restart_delay: 100,
      instances: '1',
      exec_mode: 'cluster',
      //wait_ready: true,
      env: {
        ENVIRONMENT: 'DEV',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_NAME: 'b2crypto',
        DATABASE_URL: 'mongodb://localhost:27017/b2crypto',
        PORT: 3000,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST: 'localhost',
        RABBIT_MQ_PORT: 5672,
        RABBIT_MQ_QUEUE: 'DEV',
        RABBIT_MQ_USERNAME: 'admin',
        RABBIT_MQ_PASSWORD: 'admin',
        DATABASE_REDIS_HOST: 'localhost',
        DATABASE_REDIS_USERNAME: 'b2crypto',
        DATABASE_REDIS_PASSWORD: 'b2crypto',
        DATABASE_REDIS_PORT: 6379,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: true,
        TZ: 'UTC',
      },
      env_prod: {
        ENVIRONMENT: 'PROD',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_URL: '',
        PORT: 8080,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST: '',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'PROD',
        RABBIT_MQ_USERNAME: 'b2crypto',
        RABBIT_MQ_PASSWORD: '',
        DATABASE_REDIS_HOST: '',
        DATABASE_REDIS_USERNAME: 'b2crypto',
        DATABASE_REDIS_PASSWORD: '',
        DATABASE_REDIS_PORT: 12145,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
      },
      env_stage: {
        ENVIRONMENT: 'STAGE',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_URL:
          'mongodb+srv://b2crypto:SFh59fK9mmM2ln1L@stage-b2crypto.hwml0km.mongodb.net/?retryWrites=true&w=majority&appName=stage-b2crypto',
        PORT: 8080,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST:
          'b-4dfa36c9-e0d6-4949-a093-8352b12f782d.mq.us-west-1.amazonaws.com',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'STAGE',
        RABBIT_MQ_USERNAME: 'b2crypto',
        RABBIT_MQ_PASSWORD: 'RvEEpLfH87C2rs482lOy5L6xhjC6y90b',
        DATABASE_REDIS_HOST: '',
        DATABASE_REDIS_USERNAME: 'b2crypto',
        DATABASE_REDIS_PASSWORD: '',
        DATABASE_REDIS_PORT: 12145,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
      },
    },
  ],
};
