module.exports = {
  apps: [
    {
      name: 'b2crypto-microservices',
      script: './dist-pm2/apps/b2crypto/main-microservices.js',
      watch: ['./dist-pm2/apps/b2crypto/main-microservices.js'],
      exp_backoff_restart_delay: 100,
      instances: '1',
      exec_mode: 'cluster',
      //wait_ready: true,
      env: {
        ENVIRONMENT: 'DEV',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_NAME: 'b2crypto',
        DATABASE_URL: 'mongodb://localhost:27017/b2crypto',
        PORT: 3000,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST: 'localhost',
        RABBIT_MQ_PORT: 5672,
        RABBIT_MQ_QUEUE: 'DEV',
        RABBIT_MQ_USERNAME: 'admin',
        RABBIT_MQ_PASSWORD: 'admin',
        REDIS_HOST: 'localhost',
        REDIS_USERNAME: 'b2crypto',
        REDIS_PASSWORD: 'b2crypto',
        REDIS_PORT: 6379,
        CACHE_TTL: 10,
        CACHE_MAX_ITEMS: 5,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: true,
        TZ: 'UTC',
        AWS_SES_FROM_DEFAULT: 'no-reply@b2crypto.com',
        AWS_SES_HOST: 'email-smtp.eu-west-3.amazonaws.com',
        AWS_SES_PORT: '587',
        AWS_SES_SMTP_USERNAME: 'AKIA2YTTBOKD2OUQQSM3',
        AWS_SES_SMTP_PASSWORD: 'BDRqFuz7sRh4uO+HG+P4WqgyS1J0Muac6tdICZuTRpJ/',
        API_SECRET_KEY_DIC: {
          'sKQq91g4ctRkLElI86vMeRNIPbhUc2qyEWxgbt6CGP8=':
            'hByKl5U+zzpMibm7MiEnjEsnBHC4ntATnEhjzKRw2fw=',
        },
        POMELO_WHITELISTED_IPS:
          '34.226.254.178, 44.198.3.59, 34.223.185.46, 100.20.205.117, 127.0.0.1',
        BLOCK_BALANCE_PERCENTAGE: '0.1',
        POMELO_CLIENT_ID: 'BPdaVjhdJAyzPW43JI7YUM1czNoTPh2G',
        POMELO_SECRET_ID:
          'eRIIDxqovn5sBhFII7_E9aGrSu3CiU7aLpr5tw2As3-PjU78rro2Q2uoob0qw54F',
        POMELO_AUDIENCE: 'https://auth-staging.pomelo.la',
        POMELO_AUTH_GRANT_TYPE: 'client_credentials',
        POMELO_API_URL: 'https://api-sandbox.pomelo.la',
        API_KEY_CURRENCY: '79e1291da641abba50546e9f29986759',
        URL: 'https://api.exchangeratesapi.io/v1/convert',
        DEFAULT_CURRENCY_TO_CONVERT: 'USD',
      },
      env_prod: {
        ENVIRONMENT: 'PROD',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: 'false',
        PORT: 8080,
        DATABASE_NAME: 'b2fintech',
        DATABASE_URL:
          'mongodb+srv://b2crypto:SFh59fK9mmM2ln1L@b2fintech.kajty.mongodb.net/?retryWrites=true&w=majority&appName=b2fintech',
        RABBIT_MQ_HOST:
          'b-703c2650-67d0-4b93-a229-5338ed9e32a6.mq.us-west-1.amazonaws.com',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'PROD',
        RABBIT_MQ_USERNAME: 'b2fintech',
        RABBIT_MQ_PASSWORD: 'RvEEpLfH87C2rs482lOy5L6xhjC6y90b',
        REDIS_HOST: 'redis-10790.c15.us-east-1-2.ec2.redns.redis-cloud.com',
        REDIS_USERNAME: 'default',
        REDIS_PASSWORD: 'TPhqYUUS44CQlRkhhmkZFxDb3YH0Pdam',
        REDIS_PORT: 10790,
        CACHE_TTL: 20,
        CACHE_MAX_ITEMS: 50,
        AUTH_MAX_SECONDS_TO_REFRESH: 60,
        AUTH_SECRET: 'B2FINTECH',
        AUTH_EXPIRE_IN: '8h',
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
        AWS_SES_PORT: 587,
        AWS_SES_HOST: 'email-smtp.eu-west-3.amazonaws.com',
        AWS_SES_USERNAME: 'AKIA2YTTBOKD2OUQQSM3',
        AWS_SES_PASSWORD: 'BDRqFuz7sRh4uO+HG+P4WqgyS1J0Muac6tdICZuTRpJ/',
        DEFAULT_CURRENCY_CONVERSION_COIN: 'USD',
        AUTHORIZATIONS_BLOCK_BALANCE_PERCENTAGE: 0.1,
        POMELO_SIGNATURE_SECRET_KEY_DIC:
          '{"EPPuMej5YwXpE3VZ11tiSToKjjxveOTIJSfvMrx8QJU=":"dGh7VENzDwCpd7xe3WhETN1cv13Cbd5uTE83FZw7jQA="}',
        POMELO_WHITELISTED_IPS_CHECK: 'ON',
        POMELO_WHITELISTED_IPS:
          '34.206.159.176, 52.0.20.124, 35.84.78.117, 52.43.46.111',
        POMELO_CLIENT_ID: 'f14SLpU9fV1k8WQDWZPueiQ2ON2e41nw',
        POMELO_SECRET_ID:
          'SOYRwbv8e6_T1tVlGSZ-j8RcyKD57Zk90T-wjIE5w8D_TRaXEYX3mxHKjsZsxdCl',
        POMELO_AUDIENCE: 'https://auth-prod.pomelo.la',
        POMELO_AUTH_GRANT_TYPE: 'client_credentials',
        POMELO_API_URL: 'https://api.pomelo.la',
        CURRENCY_CONVERSION_API_KEY: '79e1291da641abba50546e9f29986759',
        CURRENCY_CONVERSION_API_URL:
          'https://api.exchangeratesapi.io/v1/convert',
        POMELO_SFTP_HOST: 'sftp-dev.pomelo.la',
        POMELO_SFTP_PORT: '22',
        POMELO_SFTP_USR: 'b2crypt',
        POMELO_SFTP_PASSPHRASE: 'b2crypto',
      },
      env_stage: {
        ENVIRONMENT: 'STAGE',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_URL:
          'mongodb+srv://b2crypto:SFh59fK9mmM2ln1L@stage-b2crypto.hwml0km.mongodb.net/?retryWrites=true&w=majority&appName=stage-b2crypto',
        PORT: 8080,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST:
          'b-4dfa36c9-e0d6-4949-a093-8352b12f782d.mq.us-west-1.amazonaws.com',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'STAGE',
        RABBIT_MQ_USERNAME: 'b2crypto',
        RABBIT_MQ_PASSWORD: 'RvEEpLfH87C2rs482lOy5L6xhjC6y90b',
        REDIS_HOST: 'redis-14419.c339.eu-west-3-1.ec2.redns.redis-cloud.com',
        REDIS_USERNAME: 'default',
        REDIS_PASSWORD: 'zNm2czhWOFWZ2ZgFMxsKjKgwCQtUuGBa',
        REDIS_PORT: 14419,
        CACHE_TTL: 20,
        CACHE_MAX_ITEMS: 50,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
        AWS_SES_FROM_DEFAULT: 'no-reply@b2crypto.com',
        AWS_SES_HOST: 'email-smtp.eu-west-3.amazonaws.com',
        AWS_SES_PORT: '587',
        AWS_SES_SMTP_USERNAME: 'AKIA2YTTBOKD2OUQQSM3',
        AWS_SES_SMTP_PASSWORD: 'BDRqFuz7sRh4uO+HG+P4WqgyS1J0Muac6tdICZuTRpJ/',
        API_SECRET_KEY_DIC: {
          'sKQq91g4ctRkLElI86vMeRNIPbhUc2qyEWxgbt6CGP8=':
            'hByKl5U+zzpMibm7MiEnjEsnBHC4ntATnEhjzKRw2fw=',
        },
        POMELO_WHITELISTED_IPS:
          '34.226.254.178, 44.198.3.59, 34.223.185.46, 100.20.205.117, 127.0.0.1',
        BLOCK_BALANCE_PERCENTAGE: '0.1',
        POMELO_CLIENT_ID: 'BPdaVjhdJAyzPW43JI7YUM1czNoTPh2G',
        POMELO_SECRET_ID:
          'eRIIDxqovn5sBhFII7_E9aGrSu3CiU7aLpr5tw2As3-PjU78rro2Q2uoob0qw54F',
        POMELO_AUDIENCE: 'https://auth-staging.pomelo.la',
        POMELO_AUTH_GRANT_TYPE: 'client_credentials',
        POMELO_API_URL: 'https://api-sandbox.pomelo.la',
        API_KEY_CURRENCY: '79e1291da641abba50546e9f29986759',
        URL: 'https://api.exchangeratesapi.io/v1/convert',
        DEFAULT_CURRENCY_TO_CONVERT: 'USD',
      },
    },
    {
      name: 'b2crypto-gateway',
      script: './dist-pm2/apps/b2crypto/main-gateway.js',
      watch: ['./dist-pm2/apps/b2crypto/main-gateway.js'],
      exp_backoff_restart_delay: 100,
      instances: '1',
      exec_mode: 'cluster',
      //wait_ready: true,
      env: {
        ENVIRONMENT: 'DEV',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_NAME: 'b2crypto',
        DATABASE_URL: 'mongodb://localhost:27017/b2crypto',
        PORT: 3000,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST: 'localhost',
        RABBIT_MQ_PORT: 5672,
        RABBIT_MQ_QUEUE: 'DEV',
        RABBIT_MQ_USERNAME: 'admin',
        RABBIT_MQ_PASSWORD: 'admin',
        REDIS_HOST: 'localhost',
        REDIS_USERNAME: 'b2crypto',
        REDIS_PASSWORD: 'b2crypto',
        REDIS_PORT: 6379,
        CACHE_TTL: 10,
        CACHE_MAX_ITEMS: 5,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: true,
        TZ: 'UTC',
        AWS_SES_FROM_DEFAULT: 'no-reply@b2crypto.com',
        AWS_SES_HOST: 'email-smtp.eu-west-3.amazonaws.com',
        AWS_SES_PORT: '587',
        AWS_SES_SMTP_USERNAME: 'AKIA2YTTBOKD2OUQQSM3',
        AWS_SES_SMTP_PASSWORD: 'BDRqFuz7sRh4uO+HG+P4WqgyS1J0Muac6tdICZuTRpJ/',
        API_SECRET_KEY_DIC: {
          'sKQq91g4ctRkLElI86vMeRNIPbhUc2qyEWxgbt6CGP8=':
            'hByKl5U+zzpMibm7MiEnjEsnBHC4ntATnEhjzKRw2fw=',
        },
        POMELO_WHITELISTED_IPS:
          '34.226.254.178, 44.198.3.59, 34.223.185.46, 100.20.205.117, 127.0.0.1',
        BLOCK_BALANCE_PERCENTAGE: '0.1',
        POMELO_CLIENT_ID: 'BPdaVjhdJAyzPW43JI7YUM1czNoTPh2G',
        POMELO_SECRET_ID:
          'eRIIDxqovn5sBhFII7_E9aGrSu3CiU7aLpr5tw2As3-PjU78rro2Q2uoob0qw54F',
        POMELO_AUDIENCE: 'https://auth-staging.pomelo.la',
        POMELO_AUTH_GRANT_TYPE: 'client_credentials',
        POMELO_API_URL: 'https://api-sandbox.pomelo.la',
        API_KEY_CURRENCY: '79e1291da641abba50546e9f29986759',
        URL: 'https://api.exchangeratesapi.io/v1/convert',
        DEFAULT_CURRENCY_TO_CONVERT: 'USD',
      },
      env_prod: {
        ENVIRONMENT: 'PROD',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: 'false',
        PORT: 8080,
        DATABASE_NAME: 'b2fintech',
        DATABASE_URL:
          'mongodb+srv://b2crypto:SFh59fK9mmM2ln1L@b2fintech.kajty.mongodb.net/?retryWrites=true&w=majority&appName=b2fintech',
        RABBIT_MQ_HOST:
          'b-703c2650-67d0-4b93-a229-5338ed9e32a6.mq.us-west-1.amazonaws.com',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'PROD',
        RABBIT_MQ_USERNAME: 'b2fintech',
        RABBIT_MQ_PASSWORD: 'RvEEpLfH87C2rs482lOy5L6xhjC6y90b',
        REDIS_HOST: 'redis-10790.c15.us-east-1-2.ec2.redns.redis-cloud.com',
        REDIS_USERNAME: 'default',
        REDIS_PASSWORD: 'TPhqYUUS44CQlRkhhmkZFxDb3YH0Pdam',
        REDIS_PORT: 10790,
        CACHE_TTL: 20,
        CACHE_MAX_ITEMS: 50,
        AUTH_MAX_SECONDS_TO_REFRESH: 60,
        AUTH_SECRET: 'B2FINTECH',
        AUTH_EXPIRE_IN: '8h',
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
        AWS_SES_PORT: 587,
        AWS_SES_HOST: 'email-smtp.eu-west-3.amazonaws.com',
        AWS_SES_USERNAME: 'AKIA2YTTBOKD2OUQQSM3',
        AWS_SES_PASSWORD: 'BDRqFuz7sRh4uO+HG+P4WqgyS1J0Muac6tdICZuTRpJ/',
        DEFAULT_CURRENCY_CONVERSION_COIN: 'USD',
        AUTHORIZATIONS_BLOCK_BALANCE_PERCENTAGE: 0.1,
        POMELO_SIGNATURE_SECRET_KEY_DIC:
          '{"EPPuMej5YwXpE3VZ11tiSToKjjxveOTIJSfvMrx8QJU=":"dGh7VENzDwCpd7xe3WhETN1cv13Cbd5uTE83FZw7jQA="}',
        POMELO_WHITELISTED_IPS_CHECK: 'ON',
        POMELO_WHITELISTED_IPS:
          '34.206.159.176, 52.0.20.124, 35.84.78.117, 52.43.46.111',
        POMELO_CLIENT_ID: 'f14SLpU9fV1k8WQDWZPueiQ2ON2e41nw',
        POMELO_SECRET_ID:
          'SOYRwbv8e6_T1tVlGSZ-j8RcyKD57Zk90T-wjIE5w8D_TRaXEYX3mxHKjsZsxdCl',
        POMELO_AUDIENCE: 'https://auth-prod.pomelo.la',
        POMELO_AUTH_GRANT_TYPE: 'client_credentials',
        POMELO_API_URL: 'https://api.pomelo.la',
        CURRENCY_CONVERSION_API_KEY: '79e1291da641abba50546e9f29986759',
        CURRENCY_CONVERSION_API_URL:
          'https://api.exchangeratesapi.io/v1/convert',
        POMELO_SFTP_HOST: 'sftp-dev.pomelo.la',
        POMELO_SFTP_PORT: '22',
        POMELO_SFTP_USR: 'b2crypt',
        POMELO_SFTP_PASSPHRASE: 'b2crypto',
      },
      env_stage: {
        ENVIRONMENT: 'STAGE',
        APP_NAME: 'B2Crypto',
        GOOGLE_2FA: false,
        DATABASE_URL:
          'mongodb+srv://b2crypto:SFh59fK9mmM2ln1L@stage-b2crypto.hwml0km.mongodb.net/?retryWrites=true&w=majority&appName=stage-b2crypto',
        PORT: 8080,
        AUTH_EXPIRE_IN: '8h',
        AUTH_SECRET: 'B2Crypto',
        AUTH_MAX_SECONDS_TO_REFRESH: '60',
        RABBIT_MQ_HOST:
          'b-4dfa36c9-e0d6-4949-a093-8352b12f782d.mq.us-west-1.amazonaws.com',
        RABBIT_MQ_PORT: 5671,
        RABBIT_MQ_QUEUE: 'STAGE',
        RABBIT_MQ_USERNAME: 'b2crypto',
        RABBIT_MQ_PASSWORD: 'RvEEpLfH87C2rs482lOy5L6xhjC6y90b',
        REDIS_HOST: 'redis-14419.c339.eu-west-3-1.ec2.redns.redis-cloud.com',
        REDIS_USERNAME: 'default',
        REDIS_PASSWORD: 'zNm2czhWOFWZ2ZgFMxsKjKgwCQtUuGBa',
        REDIS_PORT: 14419,
        CACHE_TTL: 20,
        CACHE_MAX_ITEMS: 50,
        API_KEY_EMAIL_APP: '',
        URL_API_EMAIL_APP: '',
        TESTING: false,
        TZ: 'UTC',
        AWS_SES_FROM_DEFAULT: 'no-reply@b2crypto.com',
        AWS_SES_HOST: 'email-smtp.eu-west-3.amazonaws.com',
        AWS_SES_PORT: '587',
        AWS_SES_SMTP_USERNAME: 'AKIA2YTTBOKD2OUQQSM3',
        AWS_SES_SMTP_PASSWORD: 'BDRqFuz7sRh4uO+HG+P4WqgyS1J0Muac6tdICZuTRpJ/',
        API_SECRET_KEY_DIC: {
          'sKQq91g4ctRkLElI86vMeRNIPbhUc2qyEWxgbt6CGP8=':
            'hByKl5U+zzpMibm7MiEnjEsnBHC4ntATnEhjzKRw2fw=',
        },
        POMELO_WHITELISTED_IPS:
          '34.226.254.178, 44.198.3.59, 34.223.185.46, 100.20.205.117, 127.0.0.1',
        BLOCK_BALANCE_PERCENTAGE: '0.1',
        POMELO_CLIENT_ID: 'BPdaVjhdJAyzPW43JI7YUM1czNoTPh2G',
        POMELO_SECRET_ID:
          'eRIIDxqovn5sBhFII7_E9aGrSu3CiU7aLpr5tw2As3-PjU78rro2Q2uoob0qw54F',
        POMELO_AUDIENCE: 'https://auth-staging.pomelo.la',
        POMELO_AUTH_GRANT_TYPE: 'client_credentials',
        POMELO_API_URL: 'https://api-sandbox.pomelo.la',
        API_KEY_CURRENCY: '79e1291da641abba50546e9f29986759',
        URL: 'https://api.exchangeratesapi.io/v1/convert',
        DEFAULT_CURRENCY_TO_CONVERT: 'USD',
      },
    },
  ],
};
