export enum PomeloProcessEnum {
  PURCHASE = 'DEBIT',
  WITHDRAWAL = 'DEBIT',
  EXTRACASH = 'DEBIT',
  REVERSAL_REFUND = 'DEBIT',
  REVERSAL_PAYMENT = 'DEBIT',
  REFUND = 'CREDIT',
  PAYMENT = 'CREDIT',
  REVERSAL_PURCHASE = 'CREDIT',
  REVERSAL_WITHDRAWAL = 'CREDIT',
  REVERSAL_EXTRACASH = 'CREDIT',
}
