import { AffiliateEntity } from '@affiliate/affiliate/domain/entities/affiliate.entity';
import CountryCodeEnum from '@common/common/enums/country.code.b2crypto.enum';
import DocIdTypeEnum from '@common/common/enums/DocIdTypeEnum';
import GenderEnum from '@common/common/enums/GenderEnum';
import JobModel from '@common/common/models/JobModel';
import KyCModel from '@common/common/models/KyCModel';
import LocationModel from '@common/common/models/LocationModel';
import TelephoneModel from '@common/common/models/TelephoneModel';
import { LeadEntity } from '@lead/lead/entities/lead.entity';
import { PersonInterface } from '@person/person/entities/PersonInterface';
import { TrafficEntity } from '@traffic/traffic/entities/traffic.entity';
import { UserEntity } from '@user/user/entities/user.entity';
import { ObjectId } from 'mongodb';

export class PersonEntity implements PersonInterface {
  _id?: ObjectId;
  id: ObjectId;
  name: string;
  slug: string;
  description: string;
  searchText: string;
  verifiedIdentity: boolean;
  lastName: string;
  email: string[];
  telephones: TelephoneModel[];
  phoneNumber: string;
  preRegistry = false;
  isPEP: boolean;
  hasFamilyPEP: boolean;
  rotatingContractDateAccept: Date;
  numDocId: string;
  typeDocId: DocIdTypeEnum;
  location: LocationModel;
  job: JobModel;
  birth: Date;
  gender: GenderEnum;
  kyc: KyCModel;
  user: UserEntity;
  leads: LeadEntity[];
  traffics: TrafficEntity[];
  affiliates: AffiliateEntity[];
  createdAt: Date;
  updatedAt: Date;
  nationality: CountryCodeEnum;
  country: CountryCodeEnum;
  taxIdentificationType: string;
  taxIdentificationValue: string;
  activitySector: string;
  activityCode: string;
  occupation: string;
}
