export enum WithdrawalErrorCode {
    INVALID_WALLET = 'INVALID_WALLET',
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
    INVALID_ADDRESS = 'INVALID_ADDRESS',
    INVALID_AMOUNT = 'INVALID_AMOUNT',
    FIREBLOCKS_ERROR = 'FIREBLOCKS_ERROR',
    INVALID_PREORDER = 'INVALID_PREORDER',
    EXECUTION_FAILED = 'EXECUTION_FAILED',
    NETWORK_ERROR = 'NETWORK_ERROR',
    UNSUPPORTED_NETWORK = "UNSUPPORTED_NETWORK"
}