export enum WithdrawalErrorCode {
    INVALID_WALLET = 'INVALID_WALLET',
    INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
    INVALID_ADDRESS = 'INVALID_ADDRESS',
    INVALID_AMOUNT = 'INVALID_AMOUNT',
    FIREBLOCKS_ERROR = 'FIREBLOCKS_ERROR',
    INVALID_PREORDER = 'INVALID_PREORDER',
    EXECUTION_FAILED = 'EXECUTION_FAILED',
    NETWORK_ERROR = 'NETWORK_ERROR',
    UNSUPPORTED_NETWORK = 'UNSUPPORTED_NETWORK',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    BALANCE_UPDATE_FAILED = 'BALANCE_UPDATE_FAILED',
    TRANSACTION_CREATION_FAILED = 'TRANSACTION_CREATION_FAILED',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
    VALIDATION_FAILED = "VALIDATION_FAILED"
}