enum DocIdTypeEnum {
  CEDULA_CIUDADANIA = 'CC',
  CEDULA_EXTRANJERIA = 'CE',
  PERMISO_PROTECCION_TEMPORAL = 'PPT',
  PASSPORT = 'PA',
  //DOCUMENT_NATIONAL_IDENTIFICATION = 'DNI',
}

export default DocIdTypeEnum;
