enum ResourcesEnum {
  ACCOUNT = 'ACCOUNT',
  ACTIVITY = 'ACTIVITY',
  AFFILIATE = 'AFFILIATE',
  BRAND = 'BRAND',
  CATEGORY = 'CATEGORY',
  CRM = 'CRM',
  FILE = 'FILE',
  GROUP = 'GROUP',
  IP_ADDRESS = 'IP_ADDRESS',
  LEAD = 'LEAD',
  MESSAGE = 'MESSAGE',
  PERMISSION = 'PERMISSION',
  PERSON = 'PERSON',
  PSP = 'PSP',
  PSP_ACCOUNT = 'PSP_ACCOUNT',
  ROLE = 'ROLE',
  STATS_AFFILIATE = 'STATS_AFFILIATE',
  STATUS = 'STATUS',
  TRAFFIC = 'TRAFFIC',
  TRANSFER = 'TRANSFER',
  USER = 'USER',

  CFTD = 'CFTD',
  FTD = 'FTD',
  RETENTION = 'RETENTION',

  ALL = 'ALL',

  // Menu
  VIEW_CFTD = 'VIEW_CFTD',
  TRANSFER_FTD = 'TRANSFER_FTD',
  PAYSYS = 'PAYSYS',
  MONETARY_TRANSACTION = 'MONETARY_TRANSACTION',
  STATS_TRANSFER = 'STATS_TRANSFER',
  GENERAL_LEADS = 'GENERAL_LEADS',
  DATABASE = 'DATABASE',
  DETAIL_TOTAL_FTD = 'DETAIL_TOTAL_FTD',
}

export default ResourcesEnum;
