enum TagEnum {
  CATEGORY = 'CATEGORY',
  AFFILIATE = 'AFFILIATE',
  INTEGRATION = 'INTEGRATION',
  STATUS = 'STATUS',
  COLONY = 'COLONY',
  CITY = 'CITY',
  COUNTRY = 'COUNTRY',
  CURRENCY = 'CURRENCY',
  BANK = 'BANK',
  ADDRESS = 'ADDRESS',
  STREET = 'STREET',
  ZIP_CODE = 'ZIP_CODE',
  RULE = 'RULE',
  REFERRAL_TYPE = 'REFERRAL_TYPE',
  MONETARY_TRANSACTION_TYPE = 'MONETARY_TRANSACTION_TYPE',
  MONETARY_OPERATION_TYPE = 'MONETARY_OPERATION_TYPE',
  CRM = 'CRM',
  DEPARTMENT = 'DEPARTMENT',
}

export default TagEnum;
