enum StatusAccountEnum {
  VISIBLE = 'VISIBLE',
  HIDDEN = 'HIDDEN',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
  CANCEL = 'CANCEL',
  ORDERED = 'ORDERED',
  VERIFIED = 'VERIFIED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED',
  DESTRUCTION = 'DESTRUCTION',
}

export default StatusAccountEnum;
