export enum PomeloEnum {
  POMELO_NOTIFICATION_PATH = '/transactions/v1/notifications',
  POMELO_ADJUSTMENT_PATH = '/transactions/adjustments/:type',
  POMELO_AUTHORIZATION_PATH = '/transactions/authorizations',
  POMELO_INTEGRATION_CONTROLLER = '/pomelo',
  POMELO_SENSITIVE_INFO_PATH = '/sensitive-information',
  POMELO_SHIPPING_NOTIFICATION_PATH = '/pomelo/shipping/updates',
  POMELO_SHIPPING_CARD_EVENTS = '/pomelo/cards/v1/cards/events',
  POMELO_CLIENT_PROXY = 'POMELO.CLIENT.PROXY',
  POMELO_NOTIFICATION_QUEUE = 'process-notification',
  POMELO_ADJUSTMENT_QUEUE = 'process-adjustment',
  POMELO_AUTHORIZATION_QUEUE = 'process-authorization',
  POMELO_IDEMPOTENCY_HEADER = 'x-idempotency-key',
  POMELO_APIKEY_HEADER = 'x-api-key',
  POMELO_SIGNATURE_HEADER = 'x-signature',
  POMELO_TIMESTAMP_HEADER = 'x-timestamp',
  POMELO_ENDPOINT_HEADER = 'x-endpoint',
}
