import * as pulumi from '@pulumi/pulumi';

const config = new pulumi.Config();

export const SECRETS = pulumi
  .all([
    config.requireSecret('DATABASE_URL'),
    config.requireSecret('RABBIT_MQ_HOST'),
    config.requireSecret('RABBIT_MQ_USERNAME'),
    config.requireSecret('RABBIT_MQ_PASSWORD'),
    config.requireSecret('REDIS_HOST'),
    config.requireSecret('REDIS_USERNAME'),
    config.requireSecret('REDIS_PASSWORD'),
    config.requireSecret('AUTH_SECRET'),
    config.requireSecret('AWS_SES_FROM_DEFAULT'),
    config.requireSecret('AWS_SES_HOST'),
    config.requireSecret('AWS_SES_USERNAME'),
    config.requireSecret('AWS_SES_PASSWORD'),
    config.requireSecret('POMELO_SIGNATURE_SECRET_KEY_DIC'),
    config.requireSecret('POMELO_WHITELISTED_IPS'),
    config.requireSecret('POMELO_CLIENT_ID'),
    config.requireSecret('POMELO_SECRET_ID'),
    config.requireSecret('POMELO_AUDIENCE'),
    config.requireSecret('POMELO_AUTH_GRANT_TYPE'),
    config.requireSecret('POMELO_API_URL'),
    config.requireSecret('CURRENCY_CONVERSION_API_KEY'),
    config.requireSecret('CURRENCY_CONVERSION_API_URL'),
    config.requireSecret('POMELO_SFTP_HOST'),
    config.requireSecret('POMELO_SFTP_PORT'),
    config.requireSecret('POMELO_SFTP_USR'),
    config.requireSecret('POMELO_SFTP_PASSPHRASE'),
  ])
  .apply(
    ([
      DATABASE_URL,
      RABBIT_MQ_HOST,
      RABBIT_MQ_USERNAME,
      RABBIT_MQ_PASSWORD,
      REDIS_HOST,
      REDIS_USERNAME,
      REDIS_PASSWORD,
      AUTH_SECRET,
      AWS_SES_FROM_DEFAULT,
      AWS_SES_HOST,
      AWS_SES_USERNAME,
      AWS_SES_PASSWORD,
      POMELO_SIGNATURE_SECRET_KEY_DIC,
      POMELO_WHITELISTED_IPS,
      POMELO_CLIENT_ID,
      POMELO_SECRET_ID,
      POMELO_AUDIENCE,
      POMELO_AUTH_GRANT_TYPE,
      POMELO_API_URL,
      CURRENCY_CONVERSION_API_KEY,
      CURRENCY_CONVERSION_API_URL,
      POMELO_SFTP_HOST,
      POMELO_SFTP_PORT,
      POMELO_SFTP_USR,
      POMELO_SFTP_PASSPHRASE,
    ]) => ({
      DATABASE_URL,
      RABBIT_MQ_HOST,
      RABBIT_MQ_USERNAME,
      RABBIT_MQ_PASSWORD,
      REDIS_HOST,
      REDIS_USERNAME,
      REDIS_PASSWORD,
      AUTH_SECRET,
      AWS_SES_FROM_DEFAULT,
      AWS_SES_HOST,
      AWS_SES_USERNAME,
      AWS_SES_PASSWORD,
      POMELO_SIGNATURE_SECRET_KEY_DIC,
      POMELO_WHITELISTED_IPS,
      POMELO_CLIENT_ID,
      POMELO_SECRET_ID,
      POMELO_AUDIENCE,
      POMELO_AUTH_GRANT_TYPE,
      POMELO_API_URL,
      CURRENCY_CONVERSION_API_KEY,
      CURRENCY_CONVERSION_API_URL,
      POMELO_SFTP_HOST,
      POMELO_SFTP_PORT,
      POMELO_SFTP_USR,
      POMELO_SFTP_PASSPHRASE,
    }),
  );

export const VARS_ENV = {
  COMPANY_NAME: 'b2crypto',
  PROJECT_NAME: 'monolith',
  STACK: config.require('STACK'),
  CREATED_BY: 'Pulumi IaC',
  ENVIRONMENT: config.require('ENVIRONMENT'),
  PORT: config.require('PORT'),
  APP_NAME: config.require('APP_NAME'),
  GOOGLE_2FA: config.require('GOOGLE_2FA'),
  DATABASE_NAME: config.require('DATABASE_NAME'),
  RABBIT_MQ_PORT: config.require('RABBIT_MQ_PORT'),
  RABBIT_MQ_QUEUE: config.require('RABBIT_MQ_QUEUE'),
  REDIS_PORT: config.require('REDIS_PORT'),
  CACHE_TTL: config.require('CACHE_TTL'),
  CACHE_MAX_ITEMS: config.require('CACHE_MAX_ITEMS'),
  AUTH_MAX_SECONDS_TO_REFRESH: config.require('AUTH_MAX_SECONDS_TO_REFRESH'),
  AUTH_EXPIRE_IN: config.require('AUTH_EXPIRE_IN'),
  API_KEY_EMAIL_APP: config.require('API_KEY_EMAIL_APP'),
  URL_API_EMAIL_APP: config.require('URL_API_EMAIL_APP'),
  TESTING: config.require('TESTING'),
  TZ: config.require('TZ'),
  AWS_SES_PORT: config.require('AWS_SES_PORT'),
  DEFAULT_CURRENCY_CONVERSION_COIN: config.require(
    'DEFAULT_CURRENCY_CONVERSION_COIN',
  ),
  AUTHORIZATIONS_BLOCK_BALANCE_PERCENTAGE: config.require(
    'AUTHORIZATIONS_BLOCK_BALANCE_PERCENTAGE',
  ),
  POMELO_WHITELISTED_IPS_CHECK: config.require('POMELO_WHITELISTED_IPS_CHECK'),
  VPC_CIDR_BLOCK: config.require('VPC_CIDR_BLOCK'),
  DESIRED_COUNT_TASK: config.require('DESIRED_COUNT_TASK'),
  MAX_CAPACITY_AUTOSCALING: config.require('MAX_CAPACITY_AUTOSCALING'),
  MIN_CAPACITY_AUTOSCALING: config.require('MIN_CAPACITY_AUTOSCALING'),
};
